// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSO.Server.Data;

#nullable disable

namespace SSO.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SSO.Server.Models.ApplicationClient", b =>
                {
                    b.Property<Guid>("ApplicationClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ApplicationClientId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            ApplicationClientId = new Guid("22222222-2222-2222-2222-222222222221"),
                            ClientId = "internal-portal",
                            ClientName = "Internal Web Portal",
                            IsActive = true,
                            RedirectUri = "https://portal.yourcompany.com/signin-oidc"
                        },
                        new
                        {
                            ApplicationClientId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClientId = "mobile-app",
                            ClientName = "Android Mobile App",
                            IsActive = true,
                            RedirectUri = "com.yourcompany.app://callback"
                        });
                });

            modelBuilder.Entity("SSO.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GradeId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SSO.Server.Models.ContractorProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GradeId");

                    b.ToTable("ContractorProfiles", (string)null);
                });

            modelBuilder.Entity("SSO.Server.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Admin",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "IT",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "HR",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Safety",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Mechanical",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "Civil",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Electrical",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Security",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 9,
                            DepartmentName = "CSR",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 10,
                            DepartmentName = "Projects",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SSO.Server.Models.EmployeeProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AadharNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GradeId");

                    b.ToTable("EmployeeProfiles", (string)null);
                });

            modelBuilder.Entity("SSO.Server.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("GradeId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            Band = "Band A",
                            GradeCode = "A1",
                            HierarchyLevel = 1,
                            Title = "Chairman"
                        },
                        new
                        {
                            GradeId = 2,
                            Band = "Band A",
                            GradeCode = "A2",
                            HierarchyLevel = 2,
                            Title = "Vice Chairman"
                        },
                        new
                        {
                            GradeId = 3,
                            Band = "Band A",
                            GradeCode = "A3",
                            HierarchyLevel = 3,
                            Title = "Managing Director"
                        },
                        new
                        {
                            GradeId = 4,
                            Band = "Band A",
                            GradeCode = "A4",
                            HierarchyLevel = 4,
                            Title = "Director / Senior Director"
                        },
                        new
                        {
                            GradeId = 5,
                            Band = "Band A",
                            GradeCode = "A5",
                            HierarchyLevel = 5,
                            Title = "Executive Director"
                        },
                        new
                        {
                            GradeId = 6,
                            Band = "Band B",
                            GradeCode = "B1",
                            HierarchyLevel = 6,
                            Title = "CEO"
                        },
                        new
                        {
                            GradeId = 7,
                            Band = "Band B",
                            GradeCode = "B2",
                            HierarchyLevel = 7,
                            Title = "COO"
                        },
                        new
                        {
                            GradeId = 8,
                            Band = "Band B",
                            GradeCode = "B3",
                            HierarchyLevel = 8,
                            Title = "CFO / CHRO / CIO / CITO"
                        },
                        new
                        {
                            GradeId = 9,
                            Band = "Band B",
                            GradeCode = "B4",
                            HierarchyLevel = 9,
                            Title = "Deputy CFO / CHRO / CIO / CITO"
                        },
                        new
                        {
                            GradeId = 10,
                            Band = "Band C",
                            GradeCode = "C1",
                            HierarchyLevel = 10,
                            Title = "Senior Vice President"
                        },
                        new
                        {
                            GradeId = 11,
                            Band = "Band C",
                            GradeCode = "C2",
                            HierarchyLevel = 11,
                            Title = "Vice President"
                        },
                        new
                        {
                            GradeId = 12,
                            Band = "Band C",
                            GradeCode = "C3",
                            HierarchyLevel = 12,
                            Title = "Assistant Vice President"
                        },
                        new
                        {
                            GradeId = 13,
                            Band = "Band D",
                            GradeCode = "D1",
                            HierarchyLevel = 13,
                            Title = "Senior General Manager"
                        },
                        new
                        {
                            GradeId = 14,
                            Band = "Band D",
                            GradeCode = "D2",
                            HierarchyLevel = 14,
                            Title = "General Manager"
                        },
                        new
                        {
                            GradeId = 15,
                            Band = "Band D",
                            GradeCode = "D3",
                            HierarchyLevel = 15,
                            Title = "Deputy General Manager"
                        },
                        new
                        {
                            GradeId = 16,
                            Band = "Band D",
                            GradeCode = "D4",
                            HierarchyLevel = 16,
                            Title = "Assistant General Manager"
                        },
                        new
                        {
                            GradeId = 17,
                            Band = "Band E",
                            GradeCode = "E1",
                            HierarchyLevel = 17,
                            Title = "Senior Manager"
                        },
                        new
                        {
                            GradeId = 18,
                            Band = "Band E",
                            GradeCode = "E2",
                            HierarchyLevel = 18,
                            Title = "Manager"
                        },
                        new
                        {
                            GradeId = 19,
                            Band = "Band E",
                            GradeCode = "E3",
                            HierarchyLevel = 19,
                            Title = "Deputy Manager"
                        },
                        new
                        {
                            GradeId = 20,
                            Band = "Band E",
                            GradeCode = "E4",
                            HierarchyLevel = 20,
                            Title = "Assistant Manager"
                        },
                        new
                        {
                            GradeId = 21,
                            Band = "Band F",
                            GradeCode = "F1",
                            HierarchyLevel = 21,
                            Title = "Senior Executive - Engineer / Officer"
                        },
                        new
                        {
                            GradeId = 22,
                            Band = "Band F",
                            GradeCode = "F2",
                            HierarchyLevel = 22,
                            Title = "Executive - Engineer / Officer"
                        },
                        new
                        {
                            GradeId = 23,
                            Band = "Band F",
                            GradeCode = "F3",
                            HierarchyLevel = 23,
                            Title = "Assist Executive - Assist Engineer / Assist Officer"
                        },
                        new
                        {
                            GradeId = 24,
                            Band = "Band F",
                            GradeCode = "F4",
                            HierarchyLevel = 24,
                            Title = "Junior Executive - Engineer / Officer"
                        },
                        new
                        {
                            GradeId = 25,
                            Band = "Band G",
                            GradeCode = "G1",
                            HierarchyLevel = 25,
                            Title = "Management Trainee (T-3 Colleges)"
                        },
                        new
                        {
                            GradeId = 26,
                            Band = "Band G",
                            GradeCode = "G2",
                            HierarchyLevel = 26,
                            Title = "Mining (GET)"
                        },
                        new
                        {
                            GradeId = 27,
                            Band = "Band G",
                            GradeCode = "G3",
                            HierarchyLevel = 27,
                            Title = "Graduate Engineer Trainee (GET)"
                        },
                        new
                        {
                            GradeId = 28,
                            Band = "Band G",
                            GradeCode = "G4",
                            HierarchyLevel = 28,
                            Title = "Post Graduate (M.A, MCOM, M.SC)"
                        },
                        new
                        {
                            GradeId = 29,
                            Band = "Band G",
                            GradeCode = "G5",
                            HierarchyLevel = 29,
                            Title = "Diploma Engineer Trainee (DET)"
                        },
                        new
                        {
                            GradeId = 30,
                            Band = "Band G",
                            GradeCode = "G6",
                            HierarchyLevel = 30,
                            Title = "Graduate (B.A, BCOM, B.SC)"
                        },
                        new
                        {
                            GradeId = 31,
                            Band = "Band G",
                            GradeCode = "G7",
                            HierarchyLevel = 31,
                            Title = "Apprentices"
                        },
                        new
                        {
                            GradeId = 32,
                            Band = "Band G",
                            GradeCode = "G8",
                            HierarchyLevel = 32,
                            Title = "Intern / Trainee"
                        },
                        new
                        {
                            GradeId = 33,
                            Band = "Band H",
                            GradeCode = "H1",
                            HierarchyLevel = 33,
                            Title = "Coordinator"
                        },
                        new
                        {
                            GradeId = 34,
                            Band = "Band H",
                            GradeCode = "H2",
                            HierarchyLevel = 34,
                            Title = "Assistant"
                        },
                        new
                        {
                            GradeId = 35,
                            Band = "Band H",
                            GradeCode = "H3",
                            HierarchyLevel = 35,
                            Title = "Associate"
                        },
                        new
                        {
                            GradeId = 36,
                            Band = "Band H",
                            GradeCode = "H4",
                            HierarchyLevel = 36,
                            Title = "Helper"
                        },
                        new
                        {
                            GradeId = 37,
                            Band = "Band H",
                            GradeCode = "H5",
                            HierarchyLevel = 37,
                            Title = "Support Category - Assistant"
                        });
                });

            modelBuilder.Entity("SSO.Server.Models.OneTimeToken", b =>
                {
                    b.Property<Guid>("OneTimeTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("OneTimeTokenId");

                    b.HasIndex("UserId", "Purpose", "TokenHash");

                    b.ToTable("OneTimeTokens", (string)null);
                });

            modelBuilder.Entity("SSO.Server.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ApplicationClientId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("ApplicationClientId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SSO.Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("SSO.Server.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("SSO.Server.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.Navigation("Department");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("SSO.Server.Models.ContractorProfile", b =>
                {
                    b.HasOne("SSO.Server.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("SSO.Server.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.HasOne("SSO.Server.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("SSO.Server.Models.ContractorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SSO.Server.Models.EmployeeProfile", b =>
                {
                    b.HasOne("SSO.Server.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("SSO.Server.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId");

                    b.HasOne("SSO.Server.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("SSO.Server.Models.EmployeeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Grade");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SSO.Server.Models.OneTimeToken", b =>
                {
                    b.HasOne("SSO.Server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SSO.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("SSO.Server.Models.ApplicationClient", "ApplicationClient")
                        .WithMany()
                        .HasForeignKey("ApplicationClientId");

                    b.HasOne("SSO.Server.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationClient");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
